### PR TITLE
Add JSLA as Sponsor / Cross Promote

### PR DESCRIPTION
**Pull request by ashwell**
Hey Guys, a while back @davidguttman had asked about getting a little JSLA cross promotion on the Nodeschool site for our chapter.

I kind of just did this on a whim so I'm very very open to suggestions. Basically for now I added JSLA as a  "sponsor" (which I'm not so sure about) and put a little "Brought to you by the JS.LA team" line in the top header.

Let me know what you guys think, @d48, @emkay, @jcblw, @andyburke

### CODE REVIEW

**Comment by jcblw** [comment]
I like it, jsla needs a new logo. :trollface:

**Comment by ashwell** [comment]
@jcblw so get to work on one!

**Comment by jcblw** [comment]
https://github.com/jsla/js.la/issues/161

**Comment by d48** [comment]
This is great @ashwell . @davidguttman @jcblw @etanlubeck We good with always listing js.la as sponsor?

screenshot


screenshot

**Comment by jcblw** [comment]
super down :100:

**Comment by aktary** [comment]
Any chance we can list SoCal NodeJS <http://www.meetup.com/SoCal-Node-JS/> as well?  We promote NodeSchool to our audience every time there’s an upcoming NodeSchool event.

**Comment by etanlubeck** [comment]
are we gonna use the updated one from the issue? Also, enthusiast is
spelled wrong.

On Tue, Apr 12, 2016 at 2:53 PM, Ryan Regalado <notifications@github.com>
wrote:

> This is great @ashwell <https://github.com/ashwell> . @davidguttman
> <https://github.com/davidguttman> @jcblw <https://github.com/jcblw>
> @etanlubeck <https://github.com/etanlubeck> We good with always listing
> js.la as sponsor?
>
> [image: screenshot]
> <https://camo.githubusercontent.com/7384db266baaeacdbd1615a23a5c0d1faa877b30/687474703a2f2f636f6e74656e742e73637265656e636173742e636f6d2f75736572732f5279616e2e526567616c61646f2f666f6c646572732f4a696e672f6d656469612f39316534643633642d633165302d346431632d383930642d6237326664613236643932382f30303030303131332e706e67>
>
> [image: screenshot]
> <https://camo.githubusercontent.com/4637607815d18001709485805b2bc7aa7b1c2d4d/687474703a2f2f636f6e74656e742e73637265656e636173742e636f6d2f75736572732f5279616e2e526567616c61646f2f666f6c646572732f4a696e672f6d656469612f61343962313032642d366661362d343232312d623361362d3739633762366634393465642f30303030303131342e706e67>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nodeschool/los-angeles/pull/69#issuecomment-209118044>
>



-- 
Nate Lubeck, @etanlubeck <http://www.twitter.com/etanlubeck>
http://www.natelubeck.com

**Comment by ashwell** [comment]
@etanlubeck it's spelled right in the JSON, just forgot to rebuild after I fixed it

**Comment by etanlubeck** [comment]
:+1:

**Comment by ashwell** [comment]
this better?

screen shot 2016-04-12 at 5 07 48 pm

**Comment by ashwell** [comment]
@aktary to let you know, js.la actually is a sponsor of nodeschool LA events (meaning js.la donates $$$). If SoCal Node is interested in becoming a recurring sponsor we would be more than happy to list you guys

**Comment by etanlubeck** [comment]
:+1:

**Comment by d48** [comment]
👍🏼

**Pull request merged**
