### PR TITLE
september web update and event details

### PR DESCRIPTION
**Pull request by d48**
Event for this Saturday. Will use the new site scheme @jcblw created for October event if we have one.

including @andyburke for sponsor details

screenshot

### CODE REVIEW

**Comment by jcblw** [comment]
:+1:  I can get on the theme change I think I still have it in a branch

**Comment by andyburke** [comment]
lgtm :+1:

**Comment by d48** [comment]
Awesome guys, merging

**Comment by d48** [comment]
And @jcblw just push up the theme changes if you like. Looks great to me

**Pull request merged**
