### PR TITLE
losangeles website

### LINKED ISSUE #6: Fancy Website
http://nodeschool.io/los-angeles doesn't exist and it should.

### PR DESCRIPTION
**Pull request by d48**
## Overview
first pass out our Los Angeles chapter website. We can change out the colors and logo once we have a consensus, but just wanted to get the ball rolling and have a skeleton with an example logo. This fixes #6 

Merging this will make it live on http://nodeschool.io/los-angeles

screenshot

### CODE REVIEW

**Comment by emkay** [comment]
:+1:

**Comment by d48** [comment]
sweet! going to update and remove the `ti.to` link and put TBD

**Comment by jcblw** [comment]
we might need to look at the mobile version of this its pretty broken.

**Comment by d48** [comment]
Yea, I was hoping someone else could chime in and address the css for that

**Comment by d48** [comment]
Issue #9 created

**Comment by jcblw** [comment]
oh nice yeah i can take a peak just off work!

**Comment by d48** [comment]
:+1:

**Pull request merged**
