### PR TITLE
Issue Template for NodeSchool LA Events

### PR DESCRIPTION
**Pull request by ashwell**
I have never made one of these before, nor have I used one but since we only end up with two different types of issues I took a stab at creating a template.

I don't think the template will start showing up until this is on master...

### CODE REVIEW

**Comment by d48** [comment]
awesome. I wonder if we should just add to the Wiki so it's a little bit more visible and is more github related rather than code related?

**Comment by ashwell** [comment]
to my understanding if this file gets pulled into master, anytime you create a new issue it will be pre-populated with the markdown in .github/ISSUE_TEMPLATE.md

if you don't want that to be the case then putting it in the Wiki is probably a better choice

**Comment by d48** [comment]
Ah I see. I think then the only issue is if someone that wants to pose a
question or enhancement sees this full text and has to erase it before
creating their issue. IMO that's better suited in the Wiki as something
that can be used by a NodeSchool volunteer unless there was a cool feature
where it prompts you if you want to use the template or not before
inserting in the text field

**Comment by ashwell** [comment]
cool, I'll transfer the two templates to the wiki

**Comment by ashwell** [comment]
added to wiki, https://github.com/nodeschool/los-angeles/wiki/Event-Checklist-Issue-Template

**Pull request closed without merging**
